version: '3'

services:

  frontend:
    build: frontend
    ports:
    - "4200:4200"
    container_name: front-container
    # restart: always

  backend:
    build: backend
    ports:
    - "3000:3000"
    container_name: back-container
    # restart: always
    links:
    - database

  database:
    build: database
    container_name: database_container
    # restart: always


